# Supervised Machine Learning for Prediction

## Machine Learning Based on Linear Regression

In [2]:
# Requirements
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [3]:
# Data set
mlnfb = pd.read_csv('c:/jilliepython/narcissism_and_fb_usage.csv')
mlnfb.head()

,narcissism,age,gender,fbuse
0,5,16,1,28
1,4,14,1,15
2,6,35,0,50
3,8,38,1,50
4,4,11,1,11


In [4]:
# Defining feature and lable variables
X = mlnfb[['narcissism', 'age', 'gender']] # feature variable
y = mlnfb['fbuse'] # label variable

In [5]:
# Spliting the dataset into training and test sets (30% test set, 70% training set)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
# Creating a linear regression model
model = LinearRegression()

In [7]:
# Training the model
model.fit(X_train, y_train)

LinearRegression()

In [8]:
# Checking coefficients
model.coef_

array([ 0.83694792,  0.83539937, -0.82615308])

In [9]:
# Making predictions on the test set
y_pred = model.predict(X_test)

In [ ]:
# Evaluating the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(mse)
print(r2)

# R2: Moderate performance
# MSE: Nontrivial prediction error

64.91241458897552
0.5252029275416028


## Ridge Regression

In [ ]:
# Regulararization to prevent overfitting
# Penalty for larger coefficients
# Reducing coefficient magnitude

In [33]:
# Requirements

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [34]:
# Data set
df = pd.read_csv('c:/jilliepython/youtube_usage.csv')

In [35]:
# Defining the features and target variable with the updated column names
X = df[['age', 'education', 'income', 'loneliness']]
y = df['youtubehrs']

In [36]:
# Spliting the dataset into training and test sets (30% test set, 70% training set)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

In [37]:
# Standardizing the features (important for Ridge Regression)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Ridge Regression with Lambda = 1

In [38]:
# Creating and training the ridge regression model
ridge = Ridge(alpha=1) # define penalty term, aka lambda
ridge.fit(X_train_scaled, y_train)

Ridge(alpha=1)

In [39]:
# Making predictions
y_pred_lambda1 = ridge.predict(X_test_scaled)

In [40]:
# Checking coefficients from the ridge regression model
ridge_coefficients = ridge.coef_
ridge_coefficients

array([ 2.33295481, -3.21947008,  0.050352  , 16.48655349])

### Ridge Regression with Lambda = 100

In [41]:
# Creating and training the ridge regression model
ridge = Ridge(alpha=100)
ridge.fit(X_train_scaled, y_train)

Ridge(alpha=100)

In [42]:
# Making predictions
y_pred_lambda100 = ridge.predict(X_test_scaled)

In [43]:
# Getting the coefficients from the Ridge model
ridge_coefficients = ridge.coef_
ridge_coefficients

# Increasing lambda reduced most coefficient magnitudes

array([ 2.03933315, -2.75421936,  0.07612807, 14.42858193])

In [ ]:
# Evaluating the model
mse_lambda100 = mean_squared_error(y_test, y_pred_lamda100)
r2_lambda100 = r2_score(y_test, y_pred_lamda100)
print(mse_lambda100)
print(r2_lambda100)

mse_lambda1 = mean_squared_error(y_test, y_pred_lambda1)
r2_lambda1 = r2_score(y_test, y_pred_lambda1)
print(mse_lambda1)
print(r2_lambda1)

# MSE decreased
# R2 increased
# Slightly improved generalization perforance

313.9565505035636
0.45998043533586785
309.6329223902783
0.46741727259172705


## Lasso Regression

In [ ]:
# Regulararization to prevent overfitting
# But lasso regression can shirnk some coefficients to zero

In [45]:
# Requirements

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [46]:
# Data set
df = pd.read_csv('c:/jilliepython/youtube_usage.csv')

### Lasso Regression with Lambda = 1

In [47]:
# Creating and training the lasso regression model
lasso = Lasso(alpha=1.0)  # Alpha controls the regularization strength
lasso.fit(X_train_scaled, y_train)

Lasso()

In [48]:
# Making predictions
y_pred_lamda1 = lasso.predict(X_test_scaled)

In [49]:
# Checking the coefficients from the Lasso model
lasso_coefficients = lasso.coef_
lasso_coefficients

array([ 1.34833516, -2.20207719,  0.        , 15.46445838])

In [50]:
# Evaluate the model
mse_lamda1 = mean_squared_error(y_test, y_pred_lamda1)
r2_lamda1 = r2_score(y_test, y_pred_lamda1)
print(mse_lamda1)
print(r2_lamda1)

310.2268225600122
0.4663957372531611


### Lasso Regression with Lambda = 10

In [51]:
# Creating and training the lasso regression model
lasso = Lasso(alpha=10)  # Alpha controls the regularization strength
lasso.fit(X_train_scaled, y_train)

Lasso(alpha=10)

In [52]:
# Making predictions
y_pred_lamda10 = lasso.predict(X_test_scaled)

In [53]:
# Checking the coefficients from the Lasso model
lasso_coefficients = lasso.coef_
lasso_coefficients

array([ 0.        , -0.        ,  0.        ,  6.36966325])

In [ ]:
# Evaluating the model
mse_lamda10 = mean_squared_error(y_test, y_pred_lamda10)
r2_lamda10 = r2_score(y_test, y_pred_lamda10)
print(mse_lamda10)
print(r2_lamda10)

# Increased lambda led to higher MSE and lower R2
# Lower predictive performance
# Underfitting

419.58884779073964
0.27828807343419926
